export const HOME = "/home"
export const Landing = "/"
export const PROJECTS = "/projects"
export const SERVICES = "/services"
export const ABOUT_US = "/about"
export const CONTACT_US = "/contact"
export const PROJECT_DETAIL = "/project/:projectId"
